### ISSUE TITLE
Token not found in the store

### ISSUE THREAD

**Issue by jonscherman** [media-io/ex_step_flow#87]
When I write in a workflow that :
```json
{
  "id": "accesstoken",
  "type": "template",
  "store": "BACKEND",
  "value": "{provider}_TOKEN"
}
```
The message sent in the worker queue don't take the "store" attribute : 
```json
{
  "id":"accesstoken",
  "type":"string",
  "value":"SPEECHMATICS_TOKEN"
}
```

It should be this message instead : 
```json
{
  "id": "accesstoken",
  "store":"BACKEND",
  "type":"string",
  "value":"SPEECHMATICS_TOKEN"
}
```
Thus, the token value is not found in the store because of this missing "store" attribute.

**Comment by MarcAntoine-Arnaud** [comment]
Solution is to re-add store [here](https://github.com/media-io/ex_step_flow/blob/master/lib/step_flow/step/launch.ex#L529)
Better solution is to change `type` (from `template`) to `string`
update `value` to the computed `value`

Do same thing [here](https://github.com/media-io/ex_step_flow/blob/master/lib/step_flow/step/launch.ex#L574)
